### ISSUE TITLE
The program cannot quit without ctrl+c

### ISSUE THREAD

**Issue by SimPilotAdamT** [PuffinDev/PuffinCoin#5]
Even selecting to quit the PuffinCoin program in the menu doesn't work...

Terminal output:
```Shell
[16:57:06] adam@Adam-Arch /home/adam/PuffinCoin  
> python3 ./PuffinCoin.py
[INFO] Forwarded port 8222 with UPnP


 * Serving Flask app 'puffincoin.node' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

=================================================
______       __  __ _       _____       _       
| ___ \     / _|/ _(_)     /  __ \     (_)      
| |_/ /   _| |_| |_ _ _ __ | /  \/ ___  _ _ __  
|  __/ | | |  _|  _| | '_ \| |    / _ \| | '_ \ 
| |  | |_| | | | | | | | | | \__/\ (_) | | | | |
\_|   \__,_|_| |_| |_|_| |_|\____/\___/|_|_| |_|
                                                
=================================================                           

Welcome!



MENU

w) Wallet
t) Transfer PFC
m) Mine PFC
e) Exit the Program

1| Display blockchain
2| Check balance of wallet
3| Display pending transactions
4| Display connected peers
5| Add a peer

>> e


^CException ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
[16:57:38] adam@Adam-Arch /home/adam/PuffinCoin  
> 
```

**Comment by Top-Of-Tech** [comment]
Ctrl-c won't even work for me, have to end the python task in task manager.

**Comment by SimPilotAdamT** [comment]
> Ctrl-c won't even work for me, have to end the python task in task manager.

Well damn that is smth (maybe because it isn't running in a true CLI environment...?)

I opened this issue so that either me or @PuffinDev can take a look into why it's happening, and I have no clue..... 

Have you tried running it from `cmd.exe` instead of double clicking the pyfile?

**Comment by Top-Of-Tech** [comment]
Nope, still doesn't work.

**Comment by SimPilotAdamT** [comment]
> Nope, still doesn't work.

Okay thanks, now we know it isn't specific to Linux.

**Comment by PuffinDev** [comment]
I will look into ways to kill threads soon.

**Comment by Top-Of-Tech** [comment]
You guys quit this project?

**Comment by SimPilotAdamT** [comment]
> You guys quit this project?

I'm not entirely sure about @PuffinDev, but I have got College to work on. I'm 80% sure Puffin already merged the fix to this issue in the first place anyways but in the long run, from what it looks like from Puffin's end, we're likely to migrate everything to ZirCoin, but that is so WIP atm that we haven't really quit PuffinCoin. At least not yet.

**Comment by PuffinDev** [comment]
Yea, I don't think I will be working on PuffinCoin again. Everything is being rebuilt as zircoin atm, and will be on GitHub in a few weeks. Hopefully everything goes smoothly.
